- name: deploy and init NSSF DB  to openshift
  hosts: 10.6.1.6
  vars:
    namespace: oracle-defence-nssf
    docker_registry_user: oracle
    docker_registry_password: oracle123
    push_docker_registry: hubcluster-registry-quay-quay-enterprise.apps.mgmt.next.lab
    install_path: /home/oracle/NFs/NSSF
    playbook_path: /home/oracle/telenorPlaybooks/NSSF
    custom_file: ocnssf-custom-Defence-values-22.1.1.yaml
  tasks:
  - name: oc login
    shell: "oc login -u oracle -p oracle123 https://api.secure.next.lab:6443"
    register: oc_login
    until: item in oc_login.stdout
    retries: 10
    delay: 30
    with_items:
      - Login successful

#NSSF CONFIG
  - name: import NSSF config
    shell: |
        cat {{playbook_path}}/NSSF_BACKUP.json | kubectl exec -i -n oracle-defence-nssf  $(kubectl -n oracle-defence-nssf get pods |grep ocnssf-nsconfig)  -- /bin/bash -c "cat > /tmp/NSSF_BACKUP.json"
        kubectl exec -i -n oracle-defence-nssf  $(kubectl -n oracle-defence-nssf get pods |grep ocnssf-nsconfig)  -- curl --http2-prior-knowledge http://ocnssf-ingress-gateway.oracle-defence-nssf/nnssf-configuration/v1/upload  -H 'Content-Type: application/json' -d @/tmp/NSSF_BACKUP.json
    register: nssf_config
  - name: debugging nssf_config
    debug:
      var: nssf_config
